"""add is_deleted to all models

Revision ID: 21541df42345
Revises: 9b3086a0010d
Create Date: 2025-12-29 14:49:41.617106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21541df42345'
down_revision: Union[str, Sequence[str], None] = '9b3086a0010d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('messages', sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('users', sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_deleted')
    op.drop_column('messages', 'is_deleted')
    op.drop_column('chats', 'is_deleted')
    # ### end Alembic commands ###
