"""update message

Revision ID: ccb30c464e95
Revises: ce073315aa8e
Create Date: 2025-12-08 15:07:51.115085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ccb30c464e95'
down_revision: Union[str, Sequence[str], None] = 'ce073315aa8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

message_status_enum = sa.Enum(
    'SEND',
    'DELIVERED',
    'IN_WORK',
    'COMPLETED',
    name='messagestatus'
)


def upgrade() -> None:
    """Upgrade schema."""
    message_status_enum.create(op.get_bind(), checkfirst=True)
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('status', sa.Enum('SEND', 'DELIVERED', 'IN_WORK', 'COMPLETED', name='messagestatus'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'status')
    # ### end Alembic commands ###
    message_status_enum.drop(op.get_bind(), checkfirst=True)