"""udpate file

Revision ID: d7fde5684850
Revises: a9f089996bf6
Create Date: 2026-01-03 09:08:36.482509

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7fde5684850'
down_revision: Union[str, Sequence[str], None] = 'a9f089996bf6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('file_id', sa.BigInteger(), nullable=True))
    op.create_foreign_key('fk_messages_files', 'messages', 'files', ['file_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_messages_files', 'messages', type_='foreignkey')
    op.drop_column(' uselist=False', 'file_id')
    # ### end Alembic commands ###
