"""add last_read_message_id in chat_participants

Revision ID: 5094749c94f9
Revises: 621c17e83d7c
Create Date: 2026-01-11 11:04:20.116519

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5094749c94f9'
down_revision: Union[str, Sequence[str], None] = '621c17e83d7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_participants', sa.Column('last_read_message_id', sa.BigInteger(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_participants', 'last_read_message_id')
    # ### end Alembic commands ###
