"""udpate file

Revision ID: 5ac5dda9e177
Revises: e3a6a73696a9
Create Date: 2026-01-03 09:36:43.052614

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ac5dda9e177'
down_revision: Union[str, Sequence[str], None] = 'e3a6a73696a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'files', ['message_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'files', type_='unique')
    # ### end Alembic commands ###
