"""udpate file

Revision ID: c90e88a4702e
Revises: c5a62beccc6a
Create Date: 2026-01-02 13:43:25.373719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c90e88a4702e'
down_revision: Union[str, Sequence[str], None] = 'c5a62beccc6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('url', sa.String(), nullable=False))
    op.drop_column('files', 'path')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('path', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('files', 'url')
    # ### end Alembic commands ###
