"""add index

Revision ID: 6d8f07ec5e35
Revises: 7d55f6f5ef2c
Create Date: 2026-03-17 13:50:36.468999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d8f07ec5e35'
down_revision: Union[str, Sequence[str], None] = '7d55f6f5ef2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_tasks_chat_id'), 'tasks', ['chat_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasks_chat_id'), table_name='tasks')
    # ### end Alembic commands ###
