"""add when reading messages

Revision ID: 16171c5a5118
Revises: 397038cdbfa7
Create Date: 2026-05-10 12:54:09.491564

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16171c5a5118'
down_revision: Union[str, Sequence[str], None] = '397038cdbfa7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message_read_batches',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('from_id', sa.BigInteger(), nullable=False),
    sa.Column('to_id', sa.BigInteger(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_mrb_chat_range', 'message_read_batches', ['chat_id', 'from_id', 'to_id'], unique=False)
    op.create_index(op.f('ix_message_read_batches_chat_id'), 'message_read_batches', ['chat_id'], unique=False)
    op.create_index(op.f('ix_message_read_batches_user_id'), 'message_read_batches', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_message_read_batches_user_id'), table_name='message_read_batches')
    op.drop_index(op.f('ix_message_read_batches_chat_id'), table_name='message_read_batches')
    op.drop_index('idx_mrb_chat_range', table_name='message_read_batches')
    op.drop_table('message_read_batches')
    # ### end Alembic commands ###
