"""udpate file

Revision ID: d3e566408094
Revises: 5ac5dda9e177
Create Date: 2026-01-03 09:37:45.866747

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3e566408094'
down_revision: Union[str, Sequence[str], None] = '5ac5dda9e177'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_messages_files'), 'messages', type_='foreignkey')
    op.drop_column('messages', 'file_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('file_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('fk_messages_files'), 'messages', 'files', ['file_id'], ['id'])
    # ### end Alembic commands ###
