"""change nullable in message.sender_id

Revision ID: 4869b73d1df5
Revises: e89e5fc81ae3
Create Date: 2025-09-29 21:46:11.936634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4869b73d1df5'
down_revision: Union[str, Sequence[str], None] = 'e89e5fc81ae3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'sender_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'sender_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    # ### end Alembic commands ###
